language: java
dist: trusty
jdk:
  - openjdk8
sudo: required
install: true
services:
  - docker
cache:
  directories:
    - "$HOME/.m2"
script:
  - mvn test -Dtest=com.mycompany.app.AppTest#shouldAnswerWithTrue -X -B
after_success:
  - bash <(curl -s https://codecov.io/bash)
